#!/bin/bash
#

for CHAN in 1 2 3 4
do
    python MRSStaticRRSRF/plotting/plot_static_rrsrf.py --chan  $CHAN --pdf
    python MRSStaticRRSRF/plotting/plot_static_rrsrf.py --chan  $CHAN --rfcor --pdf
done