#!/bin/bash
#

# for CSTAR in 16CygB Athalia delUMi HD163466_c1 HD2811_c1 HD2811_c2 HD2811_c3 HD2811_c4 HR5467 Jena muCol
# for CSTAR in 1998-BC1 1999-XC173 1999-XZ93
# for CSTAR in HR6538 HD37962 HD167060
for CSTAR in Henrietta_1 Henrietta_2 Polana
do
    nice -n 19 mrs_proc $CSTAR >& logs/$CSTAR".log" &
done
