#!/bin/bash
#

for CSTAR in muCol delUMi HR5467 HD2811_c1 HD2811_c2 HD2811_c3 HD2811_c4 16CygB HR6538 HD37962 HD167060 Athalia Jena

do
    nice -n 19 pfpc_proc --dithsub --det1skip $CSTAR >& logs/$CSTAR"_dithsub.log" &
done